# docker-compose.yml
services:
  backend:
    build: .
    develop:
      watch:
        - path: .
          action: rebuild
    ports:
      - "8888:8888"
    env_file:
      - ./.env.dev
    # Optional: Add environment variables, volumes, or links to other services
    # environment:
    #   DEBUG: "true"
    # volumes:
    #   - ./app:/app
    # depends_on:
    #   - redis_service
  # redis_service:
  #   image: "redis:latest"
  #   ports:
  #     - "6379:6379"
    