# docker-compose.yml
services:
  web:
    build: .
    develop:
      watch:
        - path: .
          action: rebuild
    ports:
      - "8888:8888"
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:latest
    volumes:
        - postgres_data:/var/lib/postgresql/data/
    environment:
        - POSTGRES_URL=postgres
        - POSTGRES_PASSWORD=Xx123456
        - POSTGRES_DB=postgres
  nginx:
    image: nginx:latest
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - 8080:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - web
    networks:
      - nginx_network
networks:
  nginx_network:
    driver: bridge
volumes:
  postgres_data: